### ISSUE TITLE
Compat with EladsHUD

### ISSUE THREAD

**Issue by Aeniema** [execOQ/Oxygen-LC#1]
![image](https://github.com/execOQ/Oxygen-LC/assets/117127021/d9da2549-c428-411d-9034-9debad30f7f0)

Can you add compat with EladsHUD please? Add a simple long bar option or something?

**Comment by Aeniema** [comment]
Also come join the Modding Discord and post up here <3 

https://thunderstore.io/c/lethal-company/p/consequential/Oxygen/

**Comment by Aeniema** [comment]
Also where are the Oxygen Cylinders? :S

**Comment by execOQ** [comment]
> ![image](https://private-user-images.githubusercontent.com/117127021/306386738-d9da2549-c428-411d-9034-9debad30f7f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NTcxMDcsIm5iZiI6MTcwODQ1NjgwNywicGF0aCI6Ii8xMTcxMjcwMjEvMzA2Mzg2NzM4LWQ5ZGEyNTQ5LWM0MjgtNDExZC05MDM0LTlkZWJhZDMwZjdmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQxOTIwMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YWRlMWRmYjM1MTdkZTMxOGE5ODkwMDk5NzRhMmUxNGQ4MDA0YmIxNmVmOWYxN2VmMzVkN2E1NzIwNTk5OWQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LPdE3VcgCvWDb73DvImAFsQk57bibgfzHl6iBlJRTrk)
> 
> Can you add compat with EladsHUD please? Add a simple long bar option or something?

I am planning to add support for EladsHUD. I'll probably add this in next versions.

**Comment by execOQ** [comment]
> Also where are the Oxygen Cylinders? :S Ow you just return to ship :P

Yes, so far oxygen is restored only on the ship :) I have plans to add oxygen tanks as an item.

**Comment by Paradox75831004** [comment]
@execOQ 
It's strange, when I dive into the water, the oxygen tanks immediately go to zero. And then how to survive on planets with flooding?

**Comment by Qugar** [comment]
> I am planning to add support for EladsHUD. I'll probably add this in next versions.

That would be great, at the moment it's the only reason why I haven't installed the mod yet.

I think the idea of ​​your mod is great.

**Comment by Aeniema** [comment]
> > I am planning to add support for EladsHUD. I'll probably add this in next versions.
> 
> That would be great, at the moment it's the only reason why I haven't installed the mod yet.
> 
> I think the idea of ​​your mod is great.

The mod still works and also the popup warning still show alongside being able to config Oxygen to give a more forgiving timeframe for now now having an accurate reading of oxygen levels.

**Comment by execOQ** [comment]
@Aeniema, @Qugar
Hey! I just released an update that provides support for EladesHUD!

**Comment by Qugar** [comment]
Thank you, works wonderfully. :smile:

**Comment by Aeniema** [comment]
> @Aeniema, @Qugar Hey! I just released an update that provides support for EladesHUD!

Thank you so much! Been playing around with it yesterday, all seems to be working greatly! Much appreciated for the added feature, thank you <3
