### ISSUE TITLE
[Error  :Oxygen > HUDPatch] oxygenUI is null

### ISSUE THREAD

**Issue by CoolLKKPS** [execOQ/Oxygen-LC#16]
same as topic, if u need modpack let me know
happen when creating lobby twice

**Comment by execOQ** [comment]
Hey, can you send the log file when it'll again occur? and send modpack code

**Comment by CoolLKKPS** [comment]
@execOQ u can check my modpack here: https://1drv.ms/f/s!AlwrljXcImfClQt9MgB2BOZ-XA9h?e=cX6g0c

**Comment by execOQ** [comment]
Hey, @CoolLKKPS, I fixed that in Version 1.5.2. If you catch that again, open this issue again!
