### ISSUE TITLE
CSync (Sigurd) Update - Oxygen Method Error

### ISSUE THREAD

**Issue by Aeniema** [execOQ/Oxygen-LC#17]
![image](https://github.com/execOQ/Oxygen-LC/assets/117127021/a1601409-39c4-46f8-afd5-11003ef2b178)

Since CSync's update, this error shows. Error showing since CSync v4.0.0-4.0.2 (1st April Updates).

**Comment by execOQ** [comment]
Hi. The developer of CSync recently told me that he wants to simplify some functions and I need to make some changes in the code, and when he releases an update, he'll ping me in discord, but I think he forgot... I'm checking now

**Comment by execOQ** [comment]
I think for now you can downgrade the CSync...)

**Comment by execOQ** [comment]
@Aeniema, Hi! I've just published an update with fixing it!
