### ISSUE TITLE
[V50] [Error  : Unity Log] MissingMethodException: Method not found: int .RoundManager.PlayRandomClip(UnityEngine.AudioSource,UnityEngine.AudioClip[],bool,single,int)

### ISSUE THREAD

**Issue by CoolLKKPS** [execOQ/Oxygen-LC#19]
[Error  : Unity Log] MissingMethodException: Method not found: int .RoundManager.PlayRandomClip(UnityEngine.AudioSource,UnityEngine.AudioClip[],bool,single,int)
Stack trace:
LC_API.GameInterfaceAPI.Features.Player.ShowTipInternal (System.String header, System.String message, System.Single duration, System.Boolean isWarning, System.Boolean useSave, System.String prefsKey) (at <9c282cdfc7dc4cca9fcc5df099e02800>:0)
LC_API.GameInterfaceAPI.Features.Player.ShowTip (System.String header, System.String message, System.Single duration, System.Boolean isWarning, System.Boolean useSave, System.String prefsKey) (at <9c282cdfc7dc4cca9fcc5df099e02800>:0)
LC_API.GameInterfaceAPI.Events.Patches.Internal.DisplayTipPatch.Prefix (System.String headerText, System.String bodyText, System.Boolean isWarning, System.Boolean useSave, System.String prefsKey) (at <9c282cdfc7dc4cca9fcc5df099e02800>:0)
(wrapper dynamic-method) HUDManager.DMD<HUDManager::DisplayTip>(HUDManager,string,string,bool,bool,string)
Oxygen.GameObjects.OxygenLogic.ShowNotifications () (at <3d00001a7953410a9ab3fd18b167f824>:0)
Oxygen.Patches.PlayerPatch.LateUpdate_Prefix (GameNetcodeStuff.PlayerControllerB __instance) (at <3d00001a7953410a9ab3fd18b167f824>:0)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::LateUpdate>(GameNetcodeStuff.PlayerControllerB)

**Comment by CoolLKKPS** [comment]
when oxygen are getting low

**Comment by execOQ** [comment]
> when oxygen are getting low

Hi, can you send me the log file?

**Comment by CoolLKKPS** [comment]
uh i have to say sry bc i have to update my modpack like rn so, maybe tomorrow...

**Comment by CoolLKKPS** [comment]
@execOQ invaild issue, this issue bc LC_API display warning interface method incorrect, and that conflict basically every mods

**Comment by CoolLKKPS** [comment]
since LC_API already abandoned, so i won't send feedback there, and will remove LC_API instead
