### ISSUE TITLE
[Issue] with Rosie **Moon**pack, will count breathable when in the dungeons

### ISSUE THREAD

**Issue by CoolLKKPS** [execOQ/Oxygen-LC#20]
@execOQ so that moonpack will change the environment of the dungeons, that also can count as mod area, can u (or i) able to fix that?

**Comment by execOQ** [comment]
Hi, @CoolLKKPS. Are you talking about this moonpack? https://thunderstore.io/c/lethal-company/p/RosiePies/Rosies_Moons/

Also, please, send your oxygen config

**Comment by CoolLKKPS** [comment]
ahaha, well good timing, i will send my modpack and oxygen config for u

**Comment by CoolLKKPS** [comment]
[consequential.Oxygen.zip](https://github.com/execOQ/Oxygen-LC/files/15286348/consequential.Oxygen.zip)
my private modpack Link: https://1drv.ms/f/s!AlwrljXcImfClQt9MgB2BOZ-XA9h

**Comment by execOQ** [comment]
Thanks)

**Comment by CoolLKKPS** [comment]
and yes, rosies moonpack

**Comment by CoolLKKPS** [comment]
@execOQ this function need to update now, recently LLL update may break this function already, many custom dungeons are marked as breathable

**Comment by execOQ** [comment]
I haven't checked this bug yet.. but as I remember I use game's variable to check if the player in the facility. I'll check anyway but at this point it's more likely the LLL's problem

**Comment by execOQ** [comment]
@CoolLKKPS I've just pushed an update with fix for this. it should work now

**Comment by execOQ** [comment]
I'll close it for now. reopen this issue, if it occur again
