### ISSUE TITLE
Friends can't connect

### ISSUE THREAD

**Issue by LimerBoy** [execOQ/Oxygen-LC#21]
When friend tries connect (his cmd)
`
[Warning: Unity Log] [Netcode] NetworkObject (4) children not resolved to parents by the end of frame
[Error  :Oxygen > OxygenLogic] PlayerControllerB is null
`

My cmd:
`
[Info   :LethalThings] Syncing configs!
[Info   : Unity Log] Player joined w steamId: 76561198371569085
[Info   : Unity Log] Connection approval callback! Game version of client request: 10000,76561198371569085
[Info   : Unity Log] Joining client id: 1; Local/host client id: 0
[Info   : Unity Log] Approved connection?: True. Connected players #: 1
[Info   : Unity Log] Disapproval reason:
[Warning: Unity Log] [Netcode] Deferred messages were received for a trigger of type OnSpawn with key 0, but that trigger was not received within within 1 second(s).
`

this happened after updating to 1.5.6

**Comment by execOQ** [comment]
@LimerBoy, has your friend tried connecting to you with disabled oxygen mod on both sides?

**Comment by LimerBoy** [comment]
yes, but seems most mods after update was broken,  csync mod also disallowed to connect, so we are testing all......

**Comment by execOQ** [comment]
Okay then I'll close the issue for now. reopen it if your find that it's Oxygen mod
