### ISSUE TITLE
[Huge many issues] did u test the mod? i receive so many error in my log console

### ISSUE THREAD

**Issue by CoolLKKPS** [execOQ/Oxygen-LC#24]
i will upload my modpack as soon as i finish backup the config

**Comment by execOQ** [comment]
Yes, I've done a lot of tests. Could you send me the errors?

**Comment by CoolLKKPS** [comment]
wait me about 5-10 mins

**Comment by CoolLKKPS** [comment]
here's the mod config for 1.5.6 and 1.6.0, i added some v1.5.6 config options so when i want to upgrade, i don't need to change the config again
[consequential.Oxygen.zip](https://github.com/user-attachments/files/16039803/consequential.Oxygen.zip)

**Comment by CoolLKKPS** [comment]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Oxygen.GameObjects.OxygenLogic.RunLogic () (at E:/Programming/Mods/Lethal Company/Oxygen/Oxygen/General/OxygenLogic.cs:388)
Oxygen.Patches.HUDPatch.UpdatePatch () (at E:/Programming/Mods/Lethal Company/Oxygen/Oxygen/Patches/HUDPatch.cs:24)
(wrapper dynamic-method) HUDManager.DMD<HUDManager::Update>(HUDManager)

**Comment by CoolLKKPS** [comment]
\* And EladsHUD

**Comment by execOQ** [comment]
Oh, I found the problem, I'll fix that soon. For now you can enable OxyCharger in the config and this should fix errors. After I publish fix you will be able to disable it again

**Comment by execOQ** [comment]
@CoolLKKPS, I've just pushed an update, it should fix this bug. Check, please

**Comment by CoolLKKPS** [comment]
sorry for the delay reply, i have a bit sleep at that time
will test this mod shortly, thx for ur hard work!

**Comment by CoolLKKPS** [comment]
fixed
