### ISSUE TITLE
Hard Crash: Latest Update.

### ISSUE THREAD

**Issue by Aeniema** [execOQ/Oxygen-LC#4]
In latest update I been getting a hard crash on Unity when dying, no log on it - last line is saying player died then kaput. Haven't replicated yet without any mods etc, just finished messing about so will have a look tomorrow!

**Comment by execOQ** [comment]
Are you sure this happened because of my mod? In any case, if you see this again, please send me the game logs (BepInEx/LogOutput.log).

**Comment by execOQ** [comment]
i'll close it for now)

**Comment by Aeniema** [comment]
> Are you sure this happened because of my mod? In any case, if you see this again, please send me the game logs (BepInEx/LogOutput.log).

I am so sorry! I often think I replied to stuff when I didn't enter/hit button! I am so stupid sometimes, I was saying I think the issue was fixed with the latest update at the time, for some reason I was on a previous version - I updated and regenerated config and the issue had gone.

Really sorry for the false report! <3

**Comment by execOQ** [comment]
okay, I glad the issue disappeared)

**Comment by execOQ** [comment]
> > Are you sure this happened because of my mod? In any case, if you see this again, please send me the game logs (BepInEx/LogOutput.log).
> 
> I am so sorry! I often think I replied to stuff when I didn't enter/hit button! I am so stupid sometimes, I was saying I think the issue was fixed with the latest update at the time, for some reason I was on a previous version - I updated and regenerated config and the issue had gone.
> 
> Really sorry for the false report! <3

okay, I glad the issue disappeared)
