### ISSUE TITLE
Suggestion: Different moons have different oxygen consumption

### ISSUE THREAD

**Issue by Qugar** [execOQ/Oxygen-LC#5]
Would it be possible that in the future we could set the oxygen consumption for each moon individually in the config?
I think this could be a pretty cool feature. For example, we could set a higher consumption for late game moons and thus have an extra option to adjust the level of difficulty.

I don't know how difficult it is to implement, the mod would have to recognize modded moons and then enter them in the config.

**Comment by execOQ** [comment]
Hey, I'm planning to add that) but yeah there's a problem with processing the created config, and I have not solved this yet...

**Comment by execOQ** [comment]
Hey, @Qugar, sorry for the long answer... I finally completed that feature and just pushed an update with it. I did it using the second solution you provided above. Also, in addition the mod will now display all loaded moons in the console, so it's not difficult to add to the config :)

No, it didn't offend me, no worries!

**Comment by Qugar** [comment]
Hi,

Unfortunately, the same problem occurs with the mod that I had with another mod.

I come from Germany and we write down numbers differently here, with the method your mod currently works, it automatically uses our German way, which leads to problems.
I can't tell you exactly why that is, but in the config I see that your mod does it correctly in some places and uses the German way in other places.

Correct way:
![grafik](https://github.com/execOQ/Oxygen-LC/assets/8191849/1008e782-ad89-4307-af71-778a356eaffa)

German way that leads to problems:
![grafik](https://github.com/execOQ/Oxygen-LC/assets/8191849/0bfab7c0-c086-4b5d-beea-6d6842ec0951)

Unfortunately, I don't know what causes commas to be used here instead of the usual periods.

**Comment by execOQ** [comment]
Howdy, @Qugar!

I didn't know that about German) but actually there was a problem when I moved to another version of developer platform for some reason it uses comma instead of period for float variables. I wouldn't try to solve this and just left it like that) Maybe if I could solve it now, I'd do it, but it would cause problems with the current config version.

**Comment by execOQ** [comment]
> I don't know how much opportunity you have to talk to the modder from BrutalCompanyMinus, I already had the problem with his mod and he solved it relatively quickly. That would be the only thing I could think of right now.
> 
> But I thank you for your effort. As soon as I have time to test it, I'll see if it still works if I simply swap commas and periods in those places.

I've reviewed BrutalCompanyMinus' code, and it has helped me fix the issue. I just updated my mod, and it should now work properly!

**Comment by execOQ** [comment]
yeah, and now there's periods not commas :)

**Comment by Qugar** [comment]
Wow ok, that was quick, thank you for your good work. :smiley:
