### ISSUE TITLE
[suggestion] Disable inhale SFX when at the company

### ISSUE THREAD

**Issue by ytitnE** [execOQ/Oxygen-LC#8]
Disabling the inhale SFX at the company would be nice, since I use LethalCasino, its annoying to hear it when gambling and trying to listen to music. I appreciate the work, I love this mod cause its something that I feel the vanilla game should already have. Keep up the good work!

**Comment by execOQ** [comment]
hey, I'll try to add it today in config)

**Comment by ytitnE** [comment]
Awesome! Thank you!

**Comment by execOQ** [comment]
Hey, @ytitnE, I just released an update with that feature! u can now disable the SFX in the config
